server:
  port: 8764
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/7project?ullNamePatternMatchesAll=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
