server:
  port: 8763
spring:
  redis:
    # 数据库标识，可以配置多个 redis使用不同的标识区分
    database: 0
    # redisIP地址
    host: 127.0.0.1
    # redis端口号
    port: 6379
    # redis密码
    password: 123456
    # redis连接池的配置
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
      connection-init-sql: SET NAMES utf8mb4
    name: mysql
    url: jdbc:mysql://localhost:3306/7project?ullNamePatternMatchesAll=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #扫描哪个包下的mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.mr.test_orderclass.po
