server:
  port: 8766

spring:
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
